spring.application.name=hospital
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hospital}
spring.datasource.username=postgres
spring.datasource.password=1077
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true
springdoc.swagger-ui.path=/swagger-ui.html
